# Site settings
title: Hello! I'm Oscar
description: Hello! I'm Oscar, multi-lingual software developer and CTO at Shoparize
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oscar Mărginean
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Trying out new things.
email: hello@oscar.sh
#twitter_username: lorem_ipsum
github_username:  moscar09
linkedin_url: https://www.linkedin.com/in/oscar-m%C4%83rginean-8483a259/
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
